spring:

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3307/thock_market_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

# 다른 서비스 URL (Local 환경)
custom:
  global:
    productServiceUrl: http://localhost:8082
    paymentServiceUrl: http://localhost:8084

swagger:
  server:
    url: http://localhost:8080
    description: Local API Gateway