apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: thock-prod
data:
  init-databases.sh: |
    #!/bin/sh
    set -eu

    mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
      CREATE DATABASE IF NOT EXISTS thock_member_db;
      CREATE DATABASE IF NOT EXISTS thock_product_db;
      CREATE DATABASE IF NOT EXISTS thock_market_db;
      CREATE DATABASE IF NOT EXISTS thock_payment_db;
      CREATE DATABASE IF NOT EXISTS thock_settlement_db;

      CREATE USER IF NOT EXISTS 'thock_member_db_user'@'%' IDENTIFIED BY '${MEMBER_DB_PASSWORD}';
      CREATE USER IF NOT EXISTS 'thock_product_db_user'@'%' IDENTIFIED BY '${PRODUCT_DB_PASSWORD}';
      CREATE USER IF NOT EXISTS 'thock_market_db_user'@'%' IDENTIFIED BY '${MARKET_DB_PASSWORD}';
      CREATE USER IF NOT EXISTS 'thock_payment_db_user'@'%' IDENTIFIED BY '${PAYMENT_DB_PASSWORD}';
      CREATE USER IF NOT EXISTS 'thock_settlement_db_user'@'%' IDENTIFIED BY '${SETTLEMENT_DB_PASSWORD}';

      GRANT ALL PRIVILEGES ON thock_member_db.* TO 'thock_member_db_user'@'%';
      GRANT ALL PRIVILEGES ON thock_product_db.* TO 'thock_product_db_user'@'%';
      GRANT ALL PRIVILEGES ON thock_market_db.* TO 'thock_market_db_user'@'%';
      GRANT ALL PRIVILEGES ON thock_payment_db.* TO 'thock_payment_db_user'@'%';
      GRANT ALL PRIVILEGES ON thock_settlement_db.* TO 'thock_settlement_db_user'@'%';

      FLUSH PRIVILEGES;
    EOSQL
