name: CD

on:
  pull_request:
    branches: [ "fix/301-infra-CD" ]
    types: [ closed ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push api-gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          file: api-gateway/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/api-gateway:latest

      - name: Build and Push member-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: member-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/member-service:latest

      - name: Build and Push product-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: product-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/product-service:latest

      - name: Build and Push market-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: market-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/market-service:latest

      - name: Build and Push payment-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: payment-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/payment-service:latest

      - name: Build and Push settlement-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: settlement-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: sang234/settlement-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/deploy
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
          EOF